name: Flake8 check

on:
  push:
    branches: [main]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-html

    - name: Run flake8
      run: flake8 --output-file=flake8_report/index.html main.py test_main.py constants.py

    - name: Upload flake8 report
      uses: actions/upload-artifact@v2
      with:
        name: Flake8 HTML report
        path: flake8_report/
